#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=44 blur_radius=30 color=$BG_MAIN border=$BORDER_MAIN

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/itemsa

##### For Aerospace ####
# source: https://github.com/forteleaf/sketkchybar-with-aerospace/blob/main/sketchybar/sketchybarrc
# aerospace setting
# AEROSPACE_FOCUSED_MONITOR_NO=$(aerospace list-workspaces --focused)
# AEROSPACE_LIST_OF_WINDOWS_IN_FOCUSED_MONITOR=$(aerospace list-windows --workspace $AEROSPACE_FOCUSED_MONITOR_NO | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')


default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semibold:14.0"
  background.corner_radius=5
  background.height=28
  background.color=$WHITE_10
  label.color=0xffffffff
  label.padding_left=10
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=10
  icon.color=0xffffffff
)
sketchybar --default "${default[@]}"



##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

source "$ITEM_DIR/spaces.sh"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set


##### Center
source "$ITEM_DIR/front_app.sh"
sketchybar --add item clock center \
           --set clock background.color=$BG_ALT \
                       background.border_width=1 \
                       background.border_color=$BORDER_MAIN \
                       update_freq=10 \
                       icon=􀉉 \
                       icon.color=$TN_RED \
                       icon.padding_right=5 \
                       label.color=$TN_YELLOW \
                       script="$PLUGIN_DIR/clock.sh" \

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
                        icon.padding_right=5 \
                        label.padding_left=5 \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
                         icon.padding_right=5 \
                         label.padding_left=5 \
           --subscribe battery system_woke power_source_change \
           --add alias "Stats,CPU_mini" right \
           --set "Stats,CPU_mini" icon=􀫥 \
                             icon.padding_right=0 \
                             label.padding_left=0 \
                             label.padding_right=0 \
           --add alias "Stats,RAM" right \
           --set "Stats,RAM" icon=􀫦 \
                             icon.padding_right=0 \
                             label.padding_left=0 \
                             label.padding_right=0 \
           --add alias "Stats,Disk" right \
           --set "Stats,Disk" icon=􀤂 \
                             icon.padding_right=0 \
                             label.padding_left=0 \
                             label.padding_right=0 \
           # --add alias "Stats,GPU" right \
# source "$ITEM_DIR/diskmonitor.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
